simulation_duration: 16000
boards_percentage: 0.81633
parallel_carts: 1
wood_batch: 1
boards_from_beam: 4
barking_machines: 3
beams_machines: 1
boards_machines: 2
wood_price: 250
beam_price: 495
board_price: 125
barking_duration: 90
beams_duration: 30
boards_duration: 60
input_magazine_starting_capacity: 400
input_magazine_maximal_capacity: 500
output_magazine_starting_capacity: 400
output_magazine_maximal_capacity: 500
output_magazine_beams: 80
output_magazine_boards: 1280
wood_arrived_count: 12
wood_sold_count: 12
wood_arrival_cycle_time: 60
wood_selling_cycle_time: 60
magazine_barking_transport_duration: 3
barking_beams_transport_duration: 3
beams_boards_transport_duration: 3
boards_magazine_transport_duration: 3
beams_magazine_transport_duration: 3