simulation_duration: 480
boards_percentage: 0.81633
parallel_carts: 1
wood_batch: 1
boards_from_beam: 4
barking_machines: 3
beams_machines: 1
boards_machines: 2
wood_price: 250
beam_price: 495
board_price: 125
barking_duration: 90
beams_duration: 30
boards_duration: 60
input_magazine_starting_capacity: 180
input_magazine_maximal_capacity: 250
output_magazine_starting_capacity: 180
output_magazine_maximal_capacity: 250
output_magazine_beams: 36
output_magazine_boards: 576
wood_arrived_count: 20
wood_sold_count: 20
wood_arrival_cycle_time: 120
wood_selling_cycle_time: 120
magazine_barking_transport_duration: 3
barking_beams_transport_duration: 3
beams_boards_transport_duration: 3
boards_magazine_transport_duration: 3
beams_magazine_transport_duration: 3