barking_machines: 3
beams_machines: 1
boards_machines: 2
input_magazine_starting_capacity: 0
input_magazine_maximal_capacity: 10
output_magazine_starting_capacity: 0
output_magazine_maximal_capacity: 10
simulation_duration: 12
wood_arrived_count: 0
wood_sold_count: 2
wood_arrival_cycle_time: 12
wood_selling_cycle_time: 12
wood_batch: 2
magazine_barking_transport_duration: 1
barking_beams_transport_duration: 1
beams_boards_transport_duration: 1
boards_magazine_transport_duration: 1
barking_duration: 3
beams_duration: 1
boards_duration: 2