simulation_duration: 480
beams_percentage: 0.81633
parallel_carts: 1
wood_batch: 1
barking_machines: 3
beams_machines: 1
boards_machines: 2
barking_duration: 90
beams_duration: 30
boards_duration: 60
input_magazine_starting_capacity: 180
input_magazine_maximal_capacity: 250
output_magazine_starting_capacity: 180
output_magazine_maximal_capacity: 250
wood_arrived_count: 20
wood_sold_count: 20
wood_arrival_cycle_time: 60
wood_selling_cycle_time: 60
magazine_barking_transport_duration: 3
barking_beams_transport_duration: 3
beams_boards_transport_duration: 3
boards_magazine_transport_duration: 3
beams_magazine_transport_duration: 3