barking_machines: 3
cutting_into_beams_machines: 1
cutting_into_boards_machines: 2
input_magazine_starting_capacity: 8
input_magazine_maximal_capacity: 10
output_magazine_starting_capacity: 8
output_magazine_maximal_capacity: 10
simulation_duration: 6
wood_arrived_count: 2
wood_sold_count: 2
wood_arrival_cycle_time: 3
wood_selling_cycle_time: 3
wood_batch: 2
magazine_barking_transport_duration: 2
barking_duration: 3
cutting_into_beams_duration: 1
cutting_into_boards_duration: 2